version: '3.1'


services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - ubuntu_reto3_network

networks:
  reto3_network:
    driver: bridge