version: "3.1"


services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: ip-externa-db  
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - /nfs/wordpress:/var/www/html
    restart: always
    networks:
      - ubuntu_reto3_network

networks:
  ubuntu_reto3_network:
    external: true
